files:
  - source: /
    ignore:
      - /OJBetter_Bridge
      - tools
      - .gitignore
      - LICENSE
      - /i18
      - /script
    translation: /i18n/%locale%/%original_path%/%file_name%-%locale%.%file_extension%
