files:
  - source: /
    ignore:
      - /OJBetter_Bridge
      - tools
      - .gitignore
      - LICENSE
      - /i18
      - /script
      - /*github
    translation: /i18n/%osx_locale%/%original_path%/%original_file_name%
