files:
  - source: /
    ignore:
      - /OJBetter_Bridge
      - tools
      - .gitignore
      - LICENSE
      - /i18
      - /script
      - /docs/At
    translation: /i18n/%locale%/%file_name%-%locale%.%file_extension%
