name: Sync to OSS

on:
  push:
    branches:
      - main
    paths:
      - 'resources/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ossutil
        run: |
          wget http://gosspublic.alicdn.com/ossutil/1.7.0/ossutil64
          chmod 755 ossutil64

      - name: Config ossutil
        run: |
          ./ossutil64 config -e $OSS_ENDPOINT -i $OSS_ACCESS_KEY_ID -k $OSS_ACCESS_KEY_SECRET

      - name: Sync files to OSS
        env:
          OSS_ENDPOINT: 'oss-cn-beijing.aliyuncs.com'
          OSS_BUCKET: 'aowuucdn'
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        run: |
          ./ossutil64 sync ./resources/ oss://$OSS_BUCKET/resources/
